# Fittrack CircleCI config

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest

    working_directory: ~/fit-track

    steps:
      - checkout

      # Download and cache dependencies
      #- restore_cache:
      #    keys:
      #    - v1-dependencies-{{ checksum "package.json" }}
      #j    # fallback to using the latest cache if no exact match is found
      #   - v1-dependencies-

      - run: cd client && yarn install

      #- save_cache:
      #    paths:
      #      - node_modules
      #    key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: cd client && yarn test
