# Fittrack CircleCI config

version: 2.0
jobs:
  test-front-end:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/fittrak/fittrak-client

    steps:
      - checkout
      - run: yarn install
      - run: yarn lint

  test-back-end:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/fittrak

    steps:
      - checkout
      - run: pipenv install
      - run: pipenv run fittrak/manage.py test

  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/fittrak

    steps:
      - checkout
      - run: cd fittrak-client && yarn build

workflows:
  version: 2
  test-backend-and-frontend:
    jobs:
      - test-front-end
      - test-back-end
      - build
