# Fittrack CircleCI config

version: 2.0

jobs:
  test-front-end:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout
      - run: cd fittrak-client && npm install
      - run: cd fittrak-client && npm run lint
      - run: cd fittrak-client && knpm run test-with-coverage

  test-back-end:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run: pipenv install --ignore-pipfile
      - run: |
          export DJANGO_SECRET_KEY=DUMMY
          export DJANGO_HASHIDS_SALT=DUMMY
          pipenv run fittrak/manage.py test

  build-frontend:
    docker:
      - image: circleci/node:8.10

    steps:
      - checkout
      - run: cd fittrak-client && npm install
      - run: cd fittrak-client && npm run build --no-babelrc

workflows:
  version: 2
  test-build:
    jobs:
      - test-back-end
      - test-front-end
      - build-frontend
