# Fittrack CircleCI config

version: 2
jobs:
  build_frontend_app:
    docker:
      - image: circleci/node:latest

    working_directory: ~/fittrak

    steps:
      - checkout
      - run: cd fittrak-client && yarn install
      - run: cd fittrak-client && yarn lint
