# Default values for fittrak.

containers:
  static:
    name: fittrak-static
    image: gcr.io/fittrak-212120/fittrak-static
    imageTag: v1
    containerPort: 80
  app:
    name: webapp
    image: gcr.io/fittrak-212120/fittrak-app
    imageTag: v1
    containerPort: 8000
    readinessProbe:
      httpGet:
        path: /accounts/login/
        port: 8000
      periodSeconds: 30
      timeoutSeconds: 5
      successThreshold: 1
      failureThreshold: 5
  cloudsqlProxy:
    name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy
    imageTag: 1.11

services:
  webapp:
    name: webapp-service
    type: NodePort
    ports:
      protocol: TCP
      port: 8000
      targetPort: 8000

  static:
    name: static-service
    type: NodePort
    ports:
      protocol: TCP
      port: 8080
      targetPort: 80


# TODO: There should be a better way to do this though at the moment
# it is not a major concern.
sensitive:
  pg_host: 127.0.0.1
  pg_port: 5432
  pg_database: fittrak
  django_secret_key:
  djangO_hashids_salt:
  django_email_host:
  django_email_port:
  django_email_host_user:
  django_email_host_password:
  cloudsql_db_username:
  cloudsql_db_password:
  cloudsql_instance:
