apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-django-sensitive
type: Opaque
data:
  secret_key: {{ quote .Values.sensitive.django_secret_key | b64enc }}
  hashids_salt: {{ quote .Values.sensitive.django_hashids_salt |b64enc }}
  email_host: {{ quote .Values.sensitive.django_email_host | b64enc }}
  email_host_user: {{ quote .Values.sensitive.django_email_host_user | b64enc }}
  email_host_password: {{ quote .Values.sensitive.django_email_host_password | b64enc  }}
